'use client';

// TinaCMS admin route — visual editor
// This file is auto-generated by TinaCMS. The actual admin UI lives at /admin

import { TinaAdmin } from 'tinacms';
import { TinaCloudCloudifyApiUrl } from '@tinacms/datalayer';

export default function AdminPage() {
  return (
    <div>
      <TinaAdmin />
    </div>
  );
}
